### ISSUE TITLE
可以考虑基于dex结构来做差分，例如微信tinker中的dexDiff，可以吧Apk的差分做得更小

### ISSUE THREAD

**Issue by super-h-c** [sisong/sfpatcher#1]

**Comment by sisong** [comment]
嗯  类似的二进制可执行文件也可以执行类似的算法的，和谷歌的小胡瓜Courgette方案思路类似     
概念上可以概括为公式：     
```
  diffFile  :=diff(decompile(oldArchive),decompile(newArchive))
  newArchive:=recompile(patch(decompile(oldArchive),diffFile))
```
其实我在2006年就有类似的想法了，并且实际做过一些实现（见我的[blog文件](https://blog.csdn.net/housisong/article/details/658863))：diff前，根据可执行代码可以被加载在不同内存起始偏移地址的原理、汇编码或者其他原理等，识别出可执行程序中所有的的绝对地址和偏移地址，替换成某种”标签“语义，然后再执行diff； patch时还原这些标签为实际值就好了。      
只处理地址值， 缩小范围是为了decompile和recompile的速度，而不是整个可执行程序的反编译和重编译；因为我那时(2006年)发现可执行代码大部分”无效“差异数据实际上都是这些地方造成的，而这些数据的位置是可以diff时找到的，并且值本身也有规律可以利用的（后来的实现只是利用这部分规律，diff源码中的覆盖线link概念的来历）。      
  那时候觉得利用地址值标签替换方案增加的复杂度划不来：比如修改了一个bug，exe文件一般大概生成200k的补丁，而处理掉这些地址值后，有时甚至可以生成20k的补丁。看似10倍的提升，但实际上，这没有用，一个完整的程序还包含其他很多资源文件等（我们那时做网络游戏的），在整个更新包中，优化的部分（180k）在整个补丁的占比实在微不足道。 （而简单利用其数值规律就可以优化掉其中的100k，剩下的就完全没有动力去增加复杂度了）   
     
sfpatcher实现也是类似的思路：针对特定的数据专门处理，思路也可以继续往下的：     
比如，很多包里还有各种png\mp3\jpg\gif等文件，是可以解压后来处理的。(参考 [precomp](https://github.com/schnaader/precomp-cpp) )         
有些游戏的资源包使用了lz4来压缩的，也是可以处理的...       
所以可以把dex、PE、ELF也看作一个格式来处理”而已“ ...       
   
（我现在还是觉得增加的复杂度可能不必要，”肉“太少；  当然，也不排除这种可能，支持添加各种格式插件？）

**Comment by super-h-c** [comment]
（我现在还是觉得增加的复杂度可能不必要，”肉“太少； 当然，也不排除这种可能，支持添加各种格式插件？）
-----------------
看了您的apkDiffPatch 和 sfpatcher，都是在做Apk方面的差分，格式方面是否会优先考虑下dex文件呢，apk升级其实dex文件是相对xml、jpg等资源是修改最频繁，主要差异还是在dex文件的修改，

**Comment by sisong** [comment]
你的意思是做一个独立的库，它针对dex格式做一个特别的优化版本；还是在针对apk的基础上继续针对dex做特别的处理来得到更小的优化补丁？（我理解的可能是指后者）        
我个人的开发资源还是有限的，如果这个库得到大量部署，那这个库的下一个版本可能会考虑这些针对性的优化       
（现在的开发计划：先完成hdiffpatch的v4版本，提供支持边下载边patch的能力，然后开发v5版本支持任意旧版本或进行过修改的版本增量升级到新版本的问题）

**Comment by super-h-c** [comment]
你的意思是做一个独立的库，它针对dex格式做一个特别的优化版本；还是在针对apk的基础上继续针对dex做特别的处理来得到更小的优化补丁？（我理解的可能是指后者）
------
是后者
目前我们在针对dex的结构去做差分，但是合成后的文件，只能保证结构上与源文件 一致，也就是同一段地址在合成包上与源包上偏移量不一样，无法保证二进制一致，也看了您的ApkDiffPatch做了一些优化工具达到二进制一致的目的保证合成Apk后安装校验能够通过。想请教下，基于dex结构去做差分的同时如何保证二进制一致呢，在ApkDiffPatch中的ApkNormal工具做了哪些处理呢？

**Comment by sisong** [comment]
ApkDiffPatch的思路上是给团队自己的apk设计的，所以就比较任性，整个zip格式是自己规定的，用ApkNormaled就是让apk包的格式变成约定的“标准”格式，然后patch的时候使用同样的约束当然能够输出同样的包格式，这样就满足了二进制一致的目的。      
这只是一种设计思路，可以参考;       
而sfpatcher因为要支持商店，无法修改源apk，但也做到了二进制一致的约束条件； 为了满足该条件，看情况放弃了一些补丁大小或者patch的执行速度，这是另一种设计思路。（-o-1做了一个设计，以部分增大补丁包大小的方式来换取patch时10倍的压缩还原速度）

**Comment by sisong** [comment]
对于dex的结构，我没有多少了解，只能随便说说思路：识别出“多余”的不必要信息（包括已知的规律和知识），在diff前移除（集中到一处也算），而这些信息可以有办法在patch时重新拿回。

**Comment by super-h-c** [comment]
用ApkNormaled就是让apk包的格式变成约定的“标准”格式
----------
这个思路挺好的，我们参考下
