### ISSUE TITLE
hello想了解下，sfpatch在android手机上的合成速度与pc上有差异吗

### ISSUE THREAD

**Issue by 94kai** [sisong/sfpatcher#10]
真机上是否会因为设备性能导致速度下降

**Comment by sisong** [comment]
是的，手机上会慢一些；    
具体数据可以看看 readme 中关于一些常用apk的性能对比数据，主要是一台笔记本PC，但最后一列有些测试了手机上patch速度。

**Comment by 94kai** [comment]
thank you
