### ISSUE TITLE
请问如何在安卓手机上运行sfpatch？

### ISSUE THREAD

**Issue by Young-Lord** [sisong/sfpatcher#3]
如题，直接运行给出的linux版本提示`bash: ./sf_diff: cannot execute binary file: Exec format error`，能否提供arm64的版本或者源代码？

**Comment by sisong** [comment]
这里提供的可执行程序只适用于评估试用, 支持x64体系的windows和linux系统。       
如果是自己团队的apk，可以优先考虑[ApkDiffPatch](https://github.com/sisong/ApkDiffPatch)方案；    
如果评估后认为需要使用sfpatcher，请邮件(见readme)联系。
