### ISSUE TITLE
请问这个完全不同是平移但是内容相同还是内容也会改变

### ISSUE THREAD

**Issue by MyEnthusiastic** [sisong/sfpatcher#4]
一个大文件在1/4处简单进行修改，如果把修改前后的2个文件分别压缩成zip文件，用二进制工具打开2个zip文件对比会发现：前面一部分的编码相同（如果前后压缩率相当，那这部分约占1/4），但后面部分的编码数据会完全不同。
根据我的理解，根据bsdiff的假设，如果只是平移，其实算法本身是可以解决的

**Comment by sisong** [comment]
不是平移，会生成完全不同的编码（类随机）。    
“如果只是平移，其实算法本身是可以解决的”   是的，这是任何合格的基于字节的diff算法都应该解决的。

**Comment by MyEnthusiastic** [comment]
"会生成完全不同的编码（类随机）"
但是我刚刚尝试了一下，两个apk之间加了几张图片，直接diff patch，发现其实并没有生成异常的diff，请问这种异常出现会有出现的条件吗

**Comment by sisong** [comment]
“一个大文件”的修改， 这里不是说修改zip中的文件  :(

**Comment by MyEnthusiastic** [comment]
原来如此 请问这个“一个大文件”可以具体一点吗？感觉一般都是小文件？

**Comment by sisong** [comment]
你自己找个大一点的文本文件，压缩出一个zip，然后在文本文件的中间位置随便做少量修改，压缩成另一个zip，然后用二进制工具对比看看两个zip文件的数据，就知道我在说什么了

**Comment by MyEnthusiastic** [comment]
似乎get到了🤔谢谢大佬！
