### ISSUE TITLE
请问sfpatcher做diff和patch的空间复杂度如何？

### ISSUE THREAD

**Issue by fojut** [sisong/sfpatcher#9]
如题

**Comment by sisong** [comment]
diff时最大内存: (newDecompressSize+ oldDecompressSize*5(or *9 when oldDecompressSize>=2GB))+O(1)
   
patch时内存： 平均接近O（1），  一般和解压缩字典大小、zip解压缩缓冲区大小、new文件大小、线程数等设置有关。
